# Generated by Django 6.1.1 on 2026-10-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0002_product_subtitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="condition",
            field=models.CharField(
                choices=[("new", "New"), ("used", "Second-hand")],
                default="new",
                max_length=10,
            ),
        ),
    ]
