# Generated by Django 6.1.1 on 2026-10-03 15:00

from django.db import migrations, models

import tests.testapp.models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0003_product_condition"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", tests.testapp.models.RichTextField()),
            ],
        ),
    ]
