# Generated by Django 6.1.1 on 2026-10-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0004_article"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailHolder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("extra", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="SlugHolder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("extra", models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name="URLHolder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("extra", models.URLField()),
            ],
        ),
    ]
