# Generated by Django 6.1.1 on 2026-10-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0005_emailholder_slugholder_urlholder"),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("title", models.CharField(max_length=200)),
            ],
        ),
    ]
