# Generated by Django 6.1.1 on 2026-10-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0006_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="Panel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("label", models.CharField(max_length=100)),
                ("heading", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=200)),
            ],
        ),
    ]
