# Generated by Django 6.1.1 on 2026-10-03 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0007_panel"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockLevel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("counted_on", models.DateField()),
                ("in_stock", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_levels",
                        to="testapp.product",
                    ),
                ),
            ],
        ),
    ]
