# Generated by Django 6.1.1 on 2026-10-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0008_stocklevel"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactCard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("handle", models.SlugField()),
                ("email", models.EmailField(max_length=254)),
                ("website", models.URLField()),
            ],
        ),
    ]
