# Generated by Django 6.1.1 on 2026-10-03 17:46

from django.db import migrations, models

import tests.testapp.models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0009_contactcard"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeHolder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("extra", tests.testapp.models.CodeField(max_length=2)),
            ],
        ),
    ]
