# Generated by Django 6.1.1 on 2026-10-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0010_codeholder"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "code",
                    models.CharField(max_length=2, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
