# Generated by Django 6.1.1 on 2026-10-03 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0014_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workshop",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workshops",
                        to="testapp.topic",
                    ),
                ),
            ],
        ),
    ]
