# Generated by Django 6.1.1 on 2026-10-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0015_workshop"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "topics",
                    models.ManyToManyField(related_name="courses", to="testapp.topic"),
                ),
            ],
        ),
    ]
