# Generated by Django 6.1.1 on 2026-10-03 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0016_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="Remark",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="testapp.note"
                    ),
                ),
            ],
        ),
    ]
