# Generated by Django 6.1.1 on 2026-10-03 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0017_remark"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageIntro",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                (
                    "page",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intro",
                        to="testapp.page",
                    ),
                ),
            ],
        ),
    ]
