# Generated by Django 6.1.1 on 2026-10-04 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0019_delivery"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeaturedProduct",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="testapp.product",
                    ),
                ),
                ("tagline", models.CharField(max_length=200)),
            ],
            bases=("testapp.product",),
        ),
    ]
