# Generated by Django 6.1.1 on 2026-10-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0025_bulletin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Leaflet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "locale",
                    models.CharField(
                        choices=[("fr", "Français"), ("en", "English")], max_length=10
                    ),
                ),
            ],
        ),
    ]
