# Generated by Django 6.1.1 on 2026-10-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0026_leaflet"),
    ]

    operations = [
        migrations.CreateModel(
            name="Memo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("locale", models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
