# Generated by Django 6.1.1 on 2026-10-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0030_dispatch"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gazette",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("language", models.CharField(blank=True, max_length=10)),
                ("language_code", models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
