# Generated by Django 6.1.1 on 2026-10-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0036_bookmark"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pamphlet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("link", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
