# Generated by Django 6.1.1 on 2026-10-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0040_shortcut"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="weight",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
