# Generated by Django 6.1.1 on 2026-10-05 15:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0047_band_musician_engagement_band_musicians"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryProxy",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("testapp.category",),
        ),
    ]
