# Generated by Django 6.1.1 on 2026-10-05 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0048_categoryproxy"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClearanceProduct",
            fields=[
                (
                    "code",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        related_name="clearance",
                        to="testapp.product",
                    ),
                ),
            ],
            bases=("testapp.product",),
        ),
    ]
