# Generated by Django 6.1.1 on 2026-10-06 22:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0049_clearanceproduct"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextPluginProxy",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("testapp.textplugin",),
        ),
    ]
