# Generated by Django 6.1.1 on 2026-10-06 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0052_depot_bin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("city", "name"), name="testapp_venue_city_name_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Seminar",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("venue_city", models.CharField(max_length=100)),
                ("venue_name", models.CharField(max_length=200)),
                (
                    "venue",
                    models.ForeignObject(
                        from_fields=["venue_city", "venue_name"],
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seminars",
                        to="testapp.venue",
                        to_fields=["city", "name"],
                    ),
                ),
            ],
        ),
    ]
