# Generated by Django 6.1.1 on 2026-10-07 07:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0053_venue_seminar"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicProxy",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("testapp.topic",),
        ),
    ]
