# Generated by Django 6.1.1 on 2026-10-07 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0060_talk"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("building", models.IntegerField()),
                ("number", models.IntegerField()),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("building", "number"),
                        name="testapp_room_building_number_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purpose", models.CharField(max_length=200)),
                ("room_building", models.IntegerField()),
                ("room_number", models.IntegerField()),
                (
                    "room",
                    models.ForeignObject(
                        from_fields=["room_building", "room_number"],
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="testapp.room",
                        to_fields=["building", "number"],
                    ),
                ),
            ],
        ),
    ]
