# Generated by Django 6.1.1 on 2026-10-07 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0061_room_booking"),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterClass",
            fields=[
                (
                    "course_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="testapp.course",
                    ),
                ),
                ("instructor", models.CharField(max_length=200)),
            ],
            bases=("testapp.course",),
        ),
    ]
