# Generated by Django 6.1.1 on 2026-10-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0062_masterclass"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "mentors",
                    models.ManyToManyField(related_name="mentees", to="testapp.person"),
                ),
            ],
        ),
    ]
