# Generated by Django 6.1.1 on 2026-10-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0064_team_tournament_match"),
    ]

    operations = [
        migrations.CreateModel(
            name="Friend",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("friends", models.ManyToManyField(to="testapp.friend")),
            ],
        ),
    ]
