# Generated by Django 6.1.1 on 2026-10-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0065_friend"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="SubjectProxy",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("testapp.subject",),
        ),
        migrations.CreateModel(
            name="Curriculum",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "subjects",
                    models.ManyToManyField(
                        related_name="curricula", to="testapp.subjectproxy"
                    ),
                ),
            ],
        ),
    ]
